language: python
python:
  - "3.6"
  - "3.7"
dist: bionic

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update          ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install hunspell; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt install -y libhunspell-dev hunspell-en-us; fi

install:
  - pip install -r requirements.txt
  - pip install coverage

script:
  - coverage run --source generativepoetry setup.py test --verbose
