language: python
python:
  - "3.6"
  - "3.7"
dist: bionic

before_install:
  - sudo apt-get update && sudo apt install -y libhunspell-dev hunspell-en-us

install:
  - pip install -r requirements.txt
  - pip install coverage

script:
  - coverage run --source generativepoetry setup.py test --verbose
